// src/constants/routes-constants.ts

export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/',
  DASHBOARD: 'dashboard',
  UPLOAD_STL: 'upload-stl',
  CUSTOMIZE: 'customize',
  PRICE: 'price',
  QUOTE: 'quote',
  CHECKOUT: 'checkout',
  SHIPPING_DETAILS: 'checkout',
  DELIVERY_PLAN: 'select-delivery',
  PAYMENT: 'payment',
  ORDER_SUCCESSFUL: 'order-successful',
  GET_QUOTES: 'get-quotes',
  SERVICES: 'services',
  ACCOUNT: 'account',
  Notification: 'notification',
  CART: 'cart',
  SUCCESS: 'order-successful',
  GOOGLE_AUTH: 'google-auth-handler',
  VERIFY_EMAIL: 'verify-email',
  FORGET_PASSWORD: 'forgot-password',
  MY_PROFILE: 'my-profile',
  MY_ORDERS: 'my-orders',
  MY_DISPUTE: 'my-dispute',
  PLACE_ORDER: 'place-order',
  PASSWORD: 'password',
  ACCOUNT_SETTINGS: 'settings',
};
